config/routes.rb
Rails.application.routes.draw do
  resources :approves

  resources :news_letters do
    collection do
      post :adding_email
      get :send_mail
      end
      member do 
        get :unsubscribe
      end
  end

 resources :teams

 devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks" }

  
  resources :blogs do
    collection do
      get :search
      get :search_sphinx
      get :latest_blogs
      get :display_category
      get :display_tags
    end
  end

resources :users do
  collection do
    post :permissions
  end
end

 root 'blogs#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
        )
      end
   end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
        @users = User.all
    end
 

 	def new
 		@user = User.new
 	end

 	def create
 		@user = User.new(user_params)
 		if @user.save
 			redirect_to user_path(@user.id)
 		else
 			render :action => "new"
 		end
 	end

 	def edit
    	@user = User.find(params[:id])
      @users = User.all
   	end

  	 def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to user_path(@user.id)
        else
      render :action => "edit"
      end
  end

  	def show
      if current_user.super_admin
        @users = User.all
      else
        flash[:notice] = "You dont have permission to Access this page"
        redirect_to blogs_path
      end
    end
	
	def destroy
    	@user = User.find(params[:id])
    	if @user.delete
    		redirect_to users_path
    	end
  	end

  def permissions
    if current_user.super_admin
  	params[:status].each do |id|
  		@user = User.find(id)
  	 @user.update_attributes(:status => true, :admin => true, :guest => false)
  	end
  	redirect_to users_path
    else
        flash[:notice] = "You dont have permission to Access this page"
        redirect_to blogs_path
    end
  end


    private
     
     # Never trust parameters from the scary internet, only allow the white list through.
     def user_params
       params.require(:user).permit(:super_admin, :admin, :status, :guest)
     end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Editing User Record</h2>
<%= render "form" %>

app/views/users/index.html.erb
 <div class="container" ><br>
    <div class="row">
     <div class="col-md-12">
        <div class="panel panel-primary filterable">
          <div class="panel-heading">
            <h3 class="panel-title">Users list</h3>
          </div>
          <div class="table-responsive">
          <table class="table" style="margin-bottom:50px;">
            <thead>
              <tr>
              <th>Email</th>
              <th>Status</th>
              <th>Role</th>
              </tr>
            </thead>
        <tbody>
        <% if @users.empty? %>
          <tr>
            <td>NO User Record Found </td>
          </tr>
        <%else%>
          <% @users.each do |user| %>
        <tr>
        <td><%= user.email %></td>
        <% if user.status? %>
            <td>Approved</td>
        <%else %>
            <td>Not Approved</td>
        <% end %>
        <% if user.super_admin? %>
          <td>Super Admin</td>
        <% elsif user.admin? %>
          <td>Admin</td>
        <% else %>
          <td>User</td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
</div>

app/views/users/new.html.erb
<h2>Editing User Record</h2>
<%= render "form" %>

app/views/users/permissions.html.erb
<h1> Blog</h1>

app/views/users/show.html.erb
<div>
<h4>Approve the Users</h4>
<%= form_tag permissions_users_path do %>
<br><div class="form-group form-group-sm">
        <div class="row">
            <div class="col-xs-2" style="text-align:center;">Selct Users:
            </div>
            
              <div class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Selct Users: <i class="fa fa-chevron-down"></i></a>
                        <div class="dropdown-menu" style="margin-left:150px">
                          <%= select_tag  :status, options_for_select((User.
                            where(status: false).map {|r| [r.email,r.id] }) ), :multiple => true, class: 'form-control' %>
                        </div>
                    </div>
        </div>
   </div><br>
   <div class="form-group" style="padding-top:100px">
        <div class="col-sm-offset-2 col-sm-10" >
          <button type="submit" class="btn btn-default" style="margin:-20px 20px 20px 20px"><%= submit_tag "Approve" %></button>
        </div>
   </div>
   <% end %>
   </div><br>
   <script type="text/javascript">
    $('.dropdown-menu').click(function(e) {
        e.stopPropagation();
    });
</script>

   <%#= select_tag  :status, options_for_select((User.
              where(status: false).map {|r| [r.email,r.id] }) ),:prompt => "Select Users" , :multiple => true %>