config/routes.rb
Rails.application.routes.draw do
  resources :approves

  resources :news_letters do
    collection do
      post :adding_email
      get :send_mail
      end
      member do 
        get :unsubscribe
      end
  end

 resources :teams

 devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks" }

  
  resources :blogs do
    collection do
      get :search
      get :search_sphinx
      get :latest_blogs
      get :display_category
      get :display_tags
    end
  end

resources :users do
  collection do
    post :permissions
  end
end

 root 'blogs#index'

end

app/models/news_letter.rb
class NewsLetter < ActiveRecord::Base
	validates_uniqueness_of :email
	validates  :email , :presence => true ,
	:length => {:minimum => 3,:maximum => 254},
	:format => {:with => /\A^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$\z/i}
end

app/controllers/news_letters_controller.rb
class NewsLettersController < ApplicationController
  before_action :set_news_letter, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.admin or current_user.super_admin
    @news_letters = NewsLetter.all
    respond_with(@news_letters)
    else
    flash[:notice] = "You dont have permission to Access this page"
    redirect_to blogs_path
  end
  end

  def show
    respond_with(@news_letter)
  end

  def new
    @news_letter = NewsLetter.new
    respond_with(@news_letter)
  end

  def edit
  end

  def create
    @news_letter = NewsLetter.new(news_letter_params)
    # if @news_letter.save
      puts "<<<<<<<<<#{@news_letter.email}>>>>>>>>>>>>>>>>>>>"

    respond_with(@news_letter)
  # end
  end

  def update
    @news_letter.update(news_letter_params)
    respond_with(@news_letter)
  end

  def destroy
    @news_letter.destroy
    respond_with(@news_letter)
  end

  def adding_email
    unless params[:email].blank?
    @news_letter = NewsLetter.new(email: params[:email],subscribed: true)
    if @news_letter.save
      NewsLetterMailer.registration_confirmation(@news_letter).deliver
        flash[:notice] = "Mail Id Is Saved Sucessfully"
       else
     flash[:warn] = "Type an valid Email Address Or It has Already Exists"
   end
   respond_to do |format|
  format.js {render inline: "location.reload();" }
    end
  else 
    flash[:warn] = "Empty Email id"
    end
  end

def unsubscribe
  @n = NewsLetter.find(params[:id])
   @n.update_attributes(:subscribed => false)
end


  private
    def set_news_letter
      @news_letter = NewsLetter.find(params[:id])
    end

    def news_letter_params
      params.require(:news_letter).permit(:email,:subscribed)
    end
end

app/helpers/news_letters_helper.rb
module NewsLettersHelper
end

app/views/news_letters/_form.html.erb
      <br><div class="container">
            <div class="row">
            <div class="col-md-12 blog-content">
            <%= form_for(@news_letter) do |f| %>
              <% if @news_letter.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@news_letter.errors.count, "error") %> prohibited this news_letter from being saved:</h2>

                  <ul>
                  <% @news_letter.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="form-group form-group-sm">
              <div class="row">
                <div class="col-xs-2" style="text-align:center;">
                  <%= f.label :email, :class => 'control-label' %>
                </div>
                <div class="col-xs-4">
                  <%= f.text_field :email, :class => 'form-control' %>
                </div>
              </div>
            </div><br>
                <%= f.submit %>
            <% end %>
            </div>
            </div>
      </div>

app/views/news_letters/edit.html.erb
<%= render 'form' %>
<br><div class="container" >
<%= link_to t('.show', :default => t("helpers.links.show")),
            @news_letter,
            :class => 'btn btn-primary' %>
<%= link_to t('.back', :default => t("helpers.links.back")),
            news_letters_path,
            :class => 'btn btn-primary' %>
</div><br>

app/views/news_letters/index.html.erb
<div class="container" ><br>
    <div class="row">
     <div class="col-md-12">
        <div class="panel panel-primary filterable">
          <div class="panel-heading">
            <h3 class="panel-title">Emails list</h3>
          </div>
          <div class="table-responsive">
          <table class="table" style="margin-bottom:50px;">
            <thead>
              <tr>
              <th>Email</th>
              <th>Actions</th>
              </tr>
            </thead>
        <tbody>
        <% if @news_letters.empty? %>
          <tr>
            <td>NO emails Found </td>
          </tr>
        <%else%>
          <% @news_letters.each do |news_letter| %>
        <tr>
        <td><%= news_letter.email %></td>
        <td style="width:50px;"><%= link_to 'Show', news_letter %></td>
        <td style="width:50px;"><%= link_to 'Edit', edit_news_letter_path(news_letter) %></td>
        <td style="width:50px;"><%= link_to 'Destroy', news_letter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>

<%= link_to t('.new', :default => t("helpers.links.add_email")),
            new_news_letter_path,
            :class => 'btn btn-primary' %>
</div>
<br>

app/views/news_letters/new.html.erb
<%= render 'form' %>
<br><div class="container" >
<%= link_to t('.back', :default => t("helpers.links.back")),
            news_letters_path,
            :class => 'btn btn-primary' %>
</div><br>

app/views/news_letters/show.html.erb
<p id="notice"><%= notice %></p>
<br><div class="container" >
            <div class="row">
                <div class="col-md-8 col-lg-9 blog-content">
                    <div class="blog-post">
                    	<h3><%= @news_letter.email %></h3>
                    </div>
                </div>
            </div>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_news_letter_path(@news_letter),
            :class => 'btn btn-primary' %>
    <%= link_to t('.back', :default => t("helpers.links.back")),
            news_letters_path,
            :class => 'btn btn-primary' %>
</div><br>

app/views/news_letters/unsubscribe.html.erb
Successfully unsubscribed